# Grype Vulnerability Exclusions

ignore:
  # False positives for netty, spring-boot vulns (https://github.com/anchore/grype/issues/431)
  - package:
      name: spring-core
      version: 5.3.24
      type: java-archive
  
  # latest json-smart installed (2.4.8) compared to 1.3.2 triggering vuln
  - package:
      name: json-smart
      type: java-archive
  - package:
      name: snakeyaml
      type: java-archive
