# Grype Vulnerability Exclusions

ignore:
  # False positives for netty, spring-boot vulns (https://github.com/anchore/grype/issues/431)
  # Packages are updated to the latest version as of 08/11/22
  - package:
      name: reactor-netty-core
      version: 1.0.24
      type: java-archive
  - package:
      name: reactor-netty-http
      version: 1.0.24
      type: java-archive
  - package:
      name: spring-core
      version: 5.3.22
      type: java-archive
  
  # latest json-smart installed (2.4.8) compared to 1.3.2 triggering vuln
  - package:
      name: json-smart
      type: java-archive
