apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-java
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-java
  template:
    metadata:
      labels:
        app: ngsa-java
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: k3d-registry.localhost:5000/ngsa-java:local
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
          - name: PROMETHEUS
            value: "true"
          - name: ZONE
            value: dev
          - name: REGION
            value: dev
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
      volumes:
        - name: secrets
          secret:
            secretName: ngsa-secrets
            defaultMode: 444

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-java
  namespace: ngsa
spec:
  ports:
  - port: 8080
    name: http
    nodePort: 30080
  type: NodePort # For external access (k3d, kind)
  selector:
    app: ngsa-java

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: ngsa
  name: ngsa-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: ngsa
  name: ngsa-vs
spec:
  hosts:
  - "*"
  gateways:
  - ngsa-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ngsa-java
        port:
          number: 8080
