apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        aadpodidbinding: {{gitops.config.mi.name}}
        app: {{gitops.name}}
        deploy: {{gitops.deploy}}
        version: beta-{{gitops.version}}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
          - name: PROMETHEUS
            value: "true"
          - name: ZONE
            value: "{{gitops.config.zone}}"
          - name: REGION
            value: "{{gitops.config.region}}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /version
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 300
            httpGet:
              path: /healthz
              port: 8080              
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: secrets
              mountPath: "/app/secrets"
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ngsa-secrets
      nodeSelector:
        agentpool: npuser01

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{gitops.name}}-vs
  namespace: {{gitops.namespace}}
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - {{gitops.name}}-{{gitops.config.region}}-pre.{{gitops.config.domain}}
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: {{gitops.name}}
